<?php
/**
 * Plantilla Word/HTML: locación comercial BGH — TIPOLOGÍA OFICINAS.
 * Variables esperadas (definidas por generar_word_contrato.php): $c, $loc_nom, $loc_dom, $loc_cuit_txt,
 * $locatario_partes, $inq1_cuit_txt, $dom_propiedad, $ciudad_prop, $detalle, $padron, $consorcio_txt,
 * $plazo, $plazo_letras, $dia_ini, $mes_ini, $anio_ini, $dia_fin, $mes_fin, $anio_fin,
 * $precio, $precio_letras, $deposito, $deposito_letras, $destino, $rubro_txt,
 * $cod1_fianza_txt, $dia_firma, $mes_firma, $anio_firma, $inq1_email.
 */
if (!isset($c)) {
    return;
}
?>
<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="ProgId" content="Word.Document">
<title>Contrato de Locación BGH Oficinas</title>
<style>
@page { size: 21cm 29.7cm; margin: 2cm; }
body, p, div { font-family: Arial, sans-serif; font-size: 10pt; text-align: justify; line-height: 1.45; margin: 0; }
p { margin: 0 0 10pt; }
.clausula { font-weight: bold; text-transform: uppercase; }
.titulo { text-align: center; font-weight: bold; font-size: 11pt; margin-bottom: 8pt; }
.subtit { text-align: center; font-weight: bold; font-size: 10pt; margin-bottom: 16pt; }
</style>
</head>
<body>

<p class="titulo">CONTRATO DE LOCACION</p>
<p class="subtit">TIPOLOGIA: OFICINAS</p>

<p><strong>PARTES CONTRATANTES:</strong> Entre, CUIT <?= htmlspecialchars($loc_cuit_txt) ?>, con domicilio en <?= htmlspecialchars($loc_dom) ?>, Tucumán, denominada en adelante LA LOCADORA, por una parte; y por otra parte, <?= htmlspecialchars($locatario_partes) ?> CUIT <?= htmlspecialchars($inq1_cuit_txt) ?>, con domicilio en calle <?= htmlspecialchars($dom_propiedad) ?> de la Provincia de Tucumán, en adelante denominado LA LOCATARIA; convienen en celebrar el presente contrato de locación comercial, el que se regirá por las cláusulas que se detallan a continuación.</p>

<p><span class="clausula">PRIMERA. OBJETO:</span> 1.- La Locadora, en su carácter de única y exclusiva propietaria da en locación a La Locataria, ésta acepta y la recibe en tal carácter, la oficina <?= htmlspecialchars($detalle !== '' ? $detalle : '……………………') ?> ubicada en <?= htmlspecialchars($dom_propiedad) ?> de la ciudad de <?= htmlspecialchars($ciudad_prop !== '' ? $ciudad_prop : 'Yerba Buena') ?>, Provincia de Tucumán, identificada en el plano de Propiedad Horizontal respectivo como unidad N º <?= htmlspecialchars($consorcio_txt) ?>, con una superficie propia de ……………, padrón de mayor extensión N º <?= htmlspecialchars($padron) ?>; en adelante denominado el ESTABLECIMIENTO LOCADO. 2.- La Locadora expresa que el Establecimiento Locado se encuentra en estado de servir al uso y goce convenido, se entrega recién pintado, debiendo la locataria restituirla en ese mismo estado. El local consta de piso ………………….. puertas de interior tipo…………… frente vidriado, lo cual es aceptado de conformidad por La locataria, asumiendo éste como riesgo propio el estado actual de los mismos, obligándose a devolverlos al fin del contrato en igual forma y condiciones.</p>

<p><span class="clausula">SEGUNDA. DESTINO:</span> El Establecimiento que se da en locación será destinado por La Locataria para uso de “<?= htmlspecialchars($rubro_txt) ?>”. La gestión y la obtención de las respectivas habilitaciones municipales serán por exclusiva cuenta, riesgo y responsabilidad de La Locataria, quedando La Locadora exonerada de toda responsabilidad al respecto. El cambio o variación de este destino, sin autorización expresa, fehaciente y por escrito de La Locadora, será causa inapelable de rescisión imputable a La Locataria.</p>

<p><span class="clausula">TERCERA. DURACION:</span> El contrato tendrá una duración de <?= (int) $plazo ?> (<?= htmlspecialchars($plazo_letras) ?>) meses comenzando a regir a partir del día <?= (int) $dia_ini ?> de <?= htmlspecialchars($mes_ini) ?> de <?= htmlspecialchars($anio_ini) ?>, o sea que vencerá indefectiblemente el día <?= (int) $dia_fin ?> de <?= htmlspecialchars($mes_fin) ?> de <?= htmlspecialchars($anio_fin) ?>. <strong>RESTITUCION:</strong> La obligación de restituir el inmueble libre de ocupantes por parte de La Locataria, se operará de pleno derecho por el mero vencimiento del plazo estipulado, y sin necesidad de requerimiento alguno por parte de La Locadora, bajo apercibimiento de iniciar la pertinente acción judicial de desalojo. Al término del Plazo de Vigencia, el Locatario deberá restituir el Inmueble a la Locadora totalmente libre de bienes, personas o efectos y en las condiciones convenidas que se detallan más adelante. La restitución del Inmueble y la firma del acta respectiva de restitución en conformidad por las partes contratantes podrá ser llevada a cabo personalmente por el Locatario, co-locatario, por el Codeudor o por la persona física que el Codeudor designe fehacientemente. La entrega por parte del locatario del inmueble locado, una vez vencido el plazo de locación estipulado, se considerará realizada únicamente mediante un acta de entrega y recepción del inmueble y sus llaves, firmada entre las partes en conformidad, una vez cumplimentada todas las obligaciones asumidas en el presente contrato. De no mediar dicha acta, el locador podrá unilateralmente, una vez vencido los términos del contrato, disponer del inmueble locado.</p>

<p><span class="clausula">CUARTA. PRECIO DEL ALQUILER:</span> El precio de esta locación se fija para todo el contrato en la suma total de PESOS <?= htmlspecialchars($precio_letras) ?> ($<?= number_format($precio, 0, ',', '.') ?>) mensuales, más expensas. Las partes manifiestan que realizan este acuerdo de absoluta buena fe y conforme lo dispuesto por el Art. 1061 del Código Civil y Comercial de la Nación, comprometiéndose a mantener actualizado el precio del alquiler durante todo el plazo de duración de la relación locativa. El alquiler se actualizará trimestralmente, según la variación trimestral que arroje el índice de precios al consumidor (IPC), de no existir dicho índice, podrá tomarse índice ICL o similar vigente. El alquiler se pacta por períodos de mes calendario completo, y aunque el locatario se mudare antes de finalizar el mes pagará íntegramente el alquiler correspondiente a ese mes. Dicho precio no incluye IVA, ni ningun otro concepto que no haya sido expresamente acordado. En caso en que se instituyese alícuota o tributo en el futuro por algún importe, el Locatario deberá sumarlo al precio del alquiler.</p>

<p><span class="clausula">QUINTA. LUGAR Y TIEMPO DE PAGO:</span> Los alquileres se abonarán por adelantado desde el día 1 al 10 de cada periodo mensual en el domicilio de La Locadora, o en el lugar que la misma indique. Queda establecido que para el caso en que La Locadora designe un ADMINISTRADOR para percibir los alquileres, éste tendrá facultades para cursar recibos y todas las comunicaciones que hagan al cumplimiento del contrato, incluso las intimaciones que por ley correspondieran formularse, aceptando La Locataria la validez de las mismas.</p>

<p><span class="clausula">SEXTA: COMPROMISORIA:</span> En caso de que alguna de las partes entienda que el valor locativo surgido de la cláusula precio del presente contrato resulta sustancialmente diferente al de la realidad locativa del momento, las mismas de común acuerdo fijaran el nuevo valor locativo. En el eventual caso de discordancia entre las partes respecto a la continuidad del del contrato, las Inmobiliarias Rojas Cornejo, Herrera&amp;Jure, podrán oficiar en carácter de mediadores entre las partes procurando acercar posiciones y acuerdos priorizando la continuidad del vínculo locativo. Los honorarios correspondientes sobre la mediación serán soportados en partes iguales.</p>

<p><span class="clausula">SEPTIMA. MORA:</span> El alquiler que no fuera abonado por La Locataria hasta el día 10 de cada mes, devengará un interés a favor de La Locadora de 2% (dos por ciento) por cada día de demora sobre el monto del alquiler, será exigible desde el dia 11 y computará sobre el precio del alquiler del mes completo. El mismo se aplicará al momento de la cancelación de lo adeudado, no estando obligada La Locadora a recibir ni aceptar ningún pago, si antes no es abonado dicho interés en su totalidad. Todo gasto de gestión de cobro generado por mora (Cartas documentos, Honorarios profesionales, impuestos, etc.) y en tramites tendientes a lograr el pago de las obligaciones asumidas en el presente contrato estarán a cargo de la locataria y formarán parte de la obligación monetarias del mes que generó dichos gastos. El importe resultante deberá ser abonado en el momento del pago del alquiler del mes en mora reclamado. Si se acumulara al mes subisiguiente, dicho interés se aplicara sobre el precio nuevo y actualizado si correspondiera. En caso que La Locataria adeude dos períodos de alquiler del Establecimiento Locado, La Locadora queda habilitada a iniciar acción judicial de desalojo en contra de aquel, preintimandolo a pagar la suma adeudada en un plazo de 10 (diez) días corridos a partir de la recepción de la intimación, consignando en la misiva el lugar de pago.</p>

<p><span class="clausula">OCTAVA. CONSERVACIÓN:</span> La Locataria puede usar y gozar del Establecimiento Locado conforme a derecho y exclusivamente para el destino correspondiente. No puede variarlo aunque ello no cause perjuicio a La Locadora. La Locataria debe mantener el Establecimiento y conservarlo en el estado en que lo recibió. No cumple con esta obligación si lo abandona sin dejar a ninguna persona a su cuidado, si lo deja abierto, o mal cerrado, por cuanto está en juego el riesgo sobre el bien, que queda descuidado y sometido a los riesgos propios que pueden provenir de una multiplicidad de factores. No se considera abandono los cierres semanales por descanso, etc. La Locataria responde por cualquier deterioro causado al establecimiento locado, incluso por visitantes ocasionales, pero no por acción de La Locadora. A los fines de preservar la seguridad la locataria se compromete en este acto a hacer revisar una vez al año la unidad locada: 1) con un gasista matriculado si tuviera conexiones de gas natural, 2) con un electricista su gabinete de electricidad y 3) con un plomero y zinguero las condiciones de desagote de cañerías internas de baño, y las canaletas de techos para evitar filtraciones, acumulación de residuos y de agua.</p>

<p><span class="clausula">NOVENA. MODIFICACIONES. MEJORAS:</span> Salvo expresa autorización del locador, se acuerda la prohibición de perforar suelo o puerta del inmueble locado como así también queda vedado plotear el frente de la propiedad. Toda ornamentación, modificación o mejora a El Establecimiento locado, sean estas necesarias o voluntarias, quedan expresamente prohibidas en especial en su aspecto exterior.- Cualquier modificación de diseño, pintura, arquitectura, o relacionada a cualquier gremio de la construcción, accesoria al inmueble principal requerirá sin excepción una autorización expresa de la locadora.</p>

<p><span class="clausula">DECIMA. REPARACIONES – USO Y GOCE DEL ESTABLECIMIENTO LOCADO:</span> 1.- En el caso que se deban efectuar reparaciones en el Establecimiento locado, originadas por cualquier causa no imputable a La Locataria, La Locadora podrá efectuar la reparación que exija el deterioro en su calidad o defecto y la locataria no podrá negarle el acceso al inmueble si el mismo fuera requerido a tal efecto o se necesitara intervenir muros/techos o accesos estructurales específicamente desde la unidad locada. Se deja convenido entre las partes que La Locataria deberá comunicar los reclamos por reparaciones urgentes a La Locadora de forma comprobable y detallada en el domicilio del presente contrato. Se establece además y de común acuerdo, que únicamente serán reparaciones urgentes la Rotura de Cañerías, filtraciones grandes del techo, y/o la Pérdida de Gas. En el caso de que las reparaciones no sean de carácter urgente, las notificaciones deberán ser realizadas de forma fehaciente, es decir, mediante carta documento al domicilio real constituido por La Locadora. 2.- La locataria podrá llevar por cuenta propia una reparación, únicamente con la expresa autorización de la locadora, evaluando de común acuerdo, de forma previa y expresa, quien afrontara dicho gasto.</p>

<p><span class="clausula">DECIMA PRIMERA. CARGAS:</span> Será a cargo de La Locataria el pago total del servicio de Electricidad (E.D.E.T.) SAT Naturgy y los gastos de instalación/retiro/mantenimiento de medidor, y cualquier otro servicio cuya instalación pueda solicitar (TV por cable, Teléfono y/o internet, etc.). Como también los gastos que dichos servicios pudieran generar por reclamos, cortes de suministro, trámites administrativos, o mora en el pago. Asimismo, deberá abonar los impuestos inherentes a su actividad, como así también el impuesto municipal (CISI) con el padrón N° <?= htmlspecialchars($padron) ?> y las expensas ordinarias. Por otra parte, La Locadora se hará cargo del pago del impuesto inmobiliario (DGR) y de las expensas extraordinarias. En todos los casos que la locadora lo requiera, La Locataria deberá entregar los comprobantes de pago de los servicios e impuestos presentando los originales de pago. Queda establecido que los montos correspondientes a servicios, no integran el precio de la Locación fijado, y por lo tanto deberán ser abonados por La Locataria en los plazos de vencimiento y hasta la fecha de desocupación. Es responsabilidad exclusiva de la locataria verificar que los números de servicio/padrón/cliente coincida con el domicilio del inmueble locado y que el pago se realice correctamente. Al finalizar la vigencia del contrato en caso de duda respecto al pago de algún periodo, de servicios o impuestos, el locador puede requerir libre deudas formal de la entidad proveedora del suministro, de rentas, de la municipalidad o de la administración de consorcio (no siendo suficiente únicamente los comprobantes de pago).-A tal efecto se dejan informados en de forma complementaria y/o mediante Addenda al presente los números de padrón y/o servicios de la unidad locada. Haber abonado el alquiler no implica haber saldado las obligaciones pendientes de expensas, impuestos y/o servicios de períodos anteriores o en curso por lo que la Locadora podrá exigir dichos pagos a los efectos de recibir futuros pagos de alquileres. El locatario deberá hacer entrega de la totalidad de los comprobantes de pago como requisito para la firma del acta de restitución del inmueble a la finalización del presente contrato.</p>

<p><span class="clausula">DECIMA SEGUNDA. TRASMISIONES:</span> Queda expresamente PROHIBIDO cualquier sublocación y/o trasmisión, parcial o total, transitoria o permanente, gratuita u onerosa y en general, a todo título y el cambio del destino.</p>

<p><span class="clausula">DECIMA TERCERA. FACULTAD DE VISITA Y VIGILANCIA:</span> La Locadora tiene derecho a inspeccionar el estado del Establecimiento Locado y puede para ello, por sí o por las personas que designe, visitar el inmueble cuando las circunstancias lo aconsejen necesario a su solo juicio, debiendo dar aviso previo a La Locataria con un mínimo de 24 (veinticuatro) horas de antelación sin causarle mayores molestias.</p>

<p><span class="clausula">DECIMA CUARTA. RESTITUCION DE LA COSA:</span> La obligación de restituir el Establecimiento Locado al término de la presente Locación, se operará de pleno derecho, por el mero vencimiento del plazo estipulado y sin necesidad de requerimiento alguno, debiendo además La Locataria: a) Estar al día en el pago de la renta, los servicios, impuestos y las expensas ordinarias del Establecimiento Locado; b) Devolver el Establecimiento Locado en las mismas condiciones generales en que lo recibió, es decir, limpio íntegramente y con todas las paredes pintadas, quedando en óptimas condiciones de habitabilidad. c) Devolver las instalaciones mobiliarias, eléctricas, de agua potable y sanitarias en las mismas condiciones de uso y funcionamiento en que las recibió; d) En el supuesto de corte del servicio de luz, La Locataria se obliga a pagar en el acto de restitución del Establecimiento Locado, las sumas de dinero que en ese momento cobraren las empresas prestatarias de esos servicios para su reconexión, en las condiciones que fueron recibidos por La Locataria. e) Si en el hipotético caso que al término de la presente Locación, La Locataria no entregara a La Locadora el Establecimiento Locado completamente limpio. La Locadora automáticamente contratará a un servicio de limpieza utilizando el depósito en garantía abonado por La Locataria para asumir dichos gastos. La Locataria queda obligada y se compromete a que en caso de no resultar suficiente el monto total del depósito en garantía para solventar los gastos de los trabajos a realizar, abonará a La Locadora la diferencia necesaria para la terminación correspondiente. f) La Locataria deberá comunicar a La Locadora, la fecha y hora en que le hará entrega del Establecimiento Locado, ya sea ello como consecuencia del vencimiento del plazo contractual o por cualquier otro motivo que conlleve la obligación de La Locataria de restituir el Establecimiento Locado a La Locadora. La constancia de que La Locataria devolvió la tenencia del inmueble locado, totalmente desocupados, libres de todo habitante y que hizo entrega de las llaves, deberá justificarse mediante documento escrito, emanado de La Locadora, no admitiéndose otro medio de prueba. Hasta la fecha de dicho documento, los alquileres, intereses moratorios, punitorios y cualquier otro concepto que correspondiere, continuarán devengándose a cargo de La Locataria.</p>

<p><span class="clausula">DECIMA QUINTA: SEGUROS:</span> La Locataria se obliga a contratar dentro de los 30 (treinta) días de firma del presente contrato, en una compañía de seguro de primer nivel, un seguro contra incendios que cubra daños totales o parciales que se produzcan en los locales e instalaciones objeto de la presente locación, o a los vecinos, como consecuencia de siniestros originados en el ámbito del inmueble o en mercadería o en los bienes depositados en el mismo. Asimismo, La Locataria estará obligado desde la vigencia del presente contrato y durante toda la ocupación del bien locado, a contratar y mantener los seguros usuales en el comercio y conforme al objeto de la presente locación. Especialmente deberá contratar: a) un seguro contra todo riesgo que cubra el inmueble en forma integral y propiedades linderas b) un seguro de responsabilidad civil que cubra eventuales daños a clientes, dependientes y terceros, como consecuencia de siniestros producidos en el bien locado, y c) un seguro de accidente de trabajo a favor de su personal en relación de dependencia, contratistas o concesionarios vinculados al inmueble. Los seguros mencionados en los acápites a) y b), La Locataria deberá realizar el correspondiente endoso a favor de La Locadora. En todos los casos se entregarán a La Locadora copias de las pólizas y sus correspondientes constancias de pago. En caso de incumplimiento, La Locadora podrá dar por rescindido el presente contrato y solicitar el inmediato desalojo del inmueble por culpa imputable a La Locataria.</p>

<p><span class="clausula">DÉCIMA SEXTA. RESOLUCION DE CONTRATO:</span> 1.- Imputable a La Locataria: La falta de pago de dos mensualidades consecutivas o el incumplimiento por parte de La Locataria de cualquiera de las cláusulas de este instrumento, en especial la segunda y la quinta, producirá la resolución del contrato siendo imputable a La Locataria, facultando a La Locadora para promover la acción judicial de desalojo y asimismo el derecho de reclamar el cobro de todas las sumas adeudadas originadas en cualquiera de la cláusulas de este contrato por vía ejecutiva, conforme lo establecido por el Código Procesal Civil y Comercial de la Provincia de Tucumán, todo ello sin necesidad de interpelación previa alguna. La mora se produce automáticamente, sin necesidad de requerimiento o interpelación de ninguna especie (art. 886 C.C.N.), pudiendo La Locadora utilizar la vía ejecutiva para el cobro de alquileres, tributos y/o cualquier otro crédito que se origine en el presente contrato. 2.- Resolución anticipada: El contrato de locación podrá ser resuelto anticipadamente por La Locataria: Si han transcurrido seis meses de la relación locativa, debiendo en tal caso, notificar en forma fehaciente su decisión a La Locadora. Si hace uso de la opción resolutiva en el primer año de vigencia de la relación locativa, deberá abonar a La Locadora, en concepto de indemnización, la suma equivalente a un mes y medio de locación al momento de desocupar el establecimiento locado, y la de un mes si la opción se ejercita transcurrido dicho plazo. En ambos casos, el mes de alquiler será el que resulte de aplicar la cláusula cuarta del presente contrato.</p>

<p><span class="clausula">DÉCIMA SEPTIMA – CONSIDERACIONES GENERALES:</span> 1.- Los impuestos que graven la actividad a ejercer por La Locataria en los inmuebles serán a su cargo en su totalidad. 2.- La gestión y la obtención de las respectivas habilitaciones municipales serán por exclusiva cuenta, riesgo y responsabilidad de La Locataria, quedando La Locadora exonerado de toda responsabilidad al respecto. 3.- El Fiador asume todas las obligaciones contractuales y extracontractuales que nacieren de la presente relación para La Locataria, hasta la restitución del inmueble locado, con conformidad de La Locadora, y se constituye en responsable solidaria de todas las obligaciones que surjan del presente contrato. Las partes acuerdan expresamente que ante los eventuales reclamos judiciales o administrativos, de terceros por relaciones impositivas/tributarias/laborales/comerciales o de cualquier otra índole que tengan como origen la actividad profesional , comercial, o privada de la locataria, los mismos serán exclusiva responsabilidad legal de la locataria y sus fiadores, y bajo ningún punto de vista procederán contra la locadora.</p>

<p><span class="clausula">DÉCIMA OCTAVA. FIANZA:</span> 1.- Afianzando todas las obligaciones contractuales y extracontractuales que nacieren de la presente relación para La Locataria, hasta la restitución de la Unidad Locada, con conformidad de La Locadora, asume como FIADORA y principal pagadora de todas las obligaciones emergentes de este contrato, que lleva implícita la solidaridad y carencia de los beneficios de excusión, división y pre interpelación, <?= htmlspecialchars($cod1_fianza_txt) ?>. 2.- Las responsabilidades de La Fiadora abarcará también la responsabilidad civil hacia terceros, que pueda surgir para La Locataria derivada de esta locación. 3.- Sustitución de fiador: En caso de insolvencia, hechos o actos dolosos o fraudulentos, pérdida de capacidad, sea de hecho o de derecho, defunción (fallecimiento), y/o, cuando exista disminución del patrimonio original de La Fiadora, La Locadora podrá exigir su sustitución, por quien reúna las cualidades pretendidas del sustituido. 4.- La Locataria cumplirá la exigencia en el plazo máximo de quince (15) días corridos, fenecido el plazo e incumplida la obligación, La Locadora podrá rescindir este contrato.</p>

<p><span class="clausula">DECIMA NOVENA. DEPOSITO DINERARIO EN GARANTIA:</span> Para garantizar el pago inmediato de los servicios y demás obligaciones que quedaren pendientes al final de la locación La Locataria garantizará el cumplimiento de sus obligaciones mediante la entrega registrada en cuenta corriente según constancia del sistema: la suma en pesos de <?= htmlspecialchars($deposito_letras) ?> ($<?= number_format($deposito, 0, ',', '.') ?>), equivalente a la garantía pactada (referencia USD en billete: a completar según acuerdo de partes). Dicha suma no devengará intereses en favor del locatario y será recibida por La Locadora. Dicho depósito será devuelto sin interés alguno, una vez cumplidas las obligaciones, por La Locadora al término de la Locación, en un plazo de hasta 30 (treinta) días de finalizado el presente contrato, una vez verificado el buen cumplimiento de La Locataria de todas las obligaciones asumidas en el mismo. Se prohíbe a La Locataria imputar el Depósito Dinerario en Garantía, al pago de alquileres, tributos, servicios y en general a cualesquiera obligaciones, anteriores a la restitución del Establecimiento Locado de conformidad.</p>

<p><span class="clausula">VIGESIMA ACTOS EXCLUSIVAMENTE ESCRITOS:</span> 1.- Ambas partes declaran y se obligan, en forma definitiva, irrevocable y como condición indispensable de esta locación, que todos los actos jurídicos únicamente se perfeccionarán por escrito y ninguno en forma oral o verbal, vedando en especial, cualesquier nuevo contrato sobre este Establecimiento Locado, fuera de los escritos y firmados, por las partes obligadas. 2.- Cuando La Locataria pretendiera quedarse en el Establecimiento Locado invocando “locación verbal”, “de palabra” o “de hecho”, prohibida en esta cláusula, pagará como cláusula penal la suma de USD75,00.- (Dólares estadounidenses setenta y cinco),diarios, en dinero efectivo, a más de las otras obligaciones pactadas en este contrato de locación. 3.- Por la importancia de las obligaciones asumidas en esta cláusula, se la destaca y la consienten en especial, como prueba de la preferente prudencia, en su lectura y aceptación.</p>

<p><span class="clausula">VIGÉSIMA PRIMERA. TRIBUTOS:</span> El pago de impuesto de sellos, timbrado o de otra índole que gravare este contrato, serán asumidos en su totalidad por La Locataria.</p>

<p><span class="clausula">VIGÉSIMA SEGUNDA. LITIGIOS - TRIBUNAL COMPETENTE:</span> Para el caso de litigio, ambas partes y La Fiadora, se someterán a la competencia judicial de los tribunales ordinarios de la ciudad de San Miguel de Tucumán, renunciando al Fuero Federal o cualquier otro que pudiere corresponder en su caso. Asimismo, también renuncian al derecho procesal de “recusación sin expresión de causa”, del juez que deba entender en caso de litigio.</p>

<p><span class="clausula">VIGESIMA TERCERA. DOMICILIOS CONSTITUIDOS – REAL Y ELECTRONICO:</span> Las partes constituyen sus domicilios reales en los mencionados anteriormente. Ahora bien, en caso que La Fiadora cambie el domicilio real constituido durante la vigencia del contrato de locación, deberá comunicar a la brevedad el nuevo domicilio a La Locadora y/o al Administrador del inmueble locado en caso que se haya designado uno. Dicha comunicación deberá efectuarse al domicilio electrónico de La Locadora o en su defecto, a los teléfonos del Corredor Inmobiliario indicados en la cláusula quinta del presente contrato. Ambas partes ratifican que las comunicaciones convenidas en el presente contrato también se podrán efectuar por vía electrónica. Las notificaciones cursadas de este modo se tendrán por válidas y plenamente eficaces (art. 75 C.C. y C.N.), ya sean judiciales o extrajudiciales. Por lo tanto, las partes constituyen sus domicilios electrónicos en las siguientes casillas de mail: a) La Locadora en herrerayllobeta@gmail.com; b) La Locataria en <?= htmlspecialchars($inq1_email !== '' ? $inq1_email : '…………………………………..') ?>; c) La Fiadora ……………………………..</p>

<p>Previa lectura y ratificación, se suscriben de conformidad, dos (2) juegos de ejemplares de igual tenor y a similar efecto de este contrato, recibiendo un ejemplar cada parte.</p>

<p style="margin-top: 24pt;">En la ciudad de San Miguel de Tucumán, a los <?= (int) $dia_firma ?> de <?= htmlspecialchars($mes_firma) ?> de <?= htmlspecialchars($anio_firma) ?>.</p>

</body>
</html>
